/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Appear: typeof import('./src/components/Input/appear.vue')['default']
    Configuration: typeof import('./src/components/Input/configuration.vue')['default']
    D: typeof import('./src/components/Input/d.vue')['default']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    Input: typeof import('./src/components/Input/input.vue')['default']
    Thumb: typeof import('./src/components/Input/thumb.vue')['default']
    Tools: typeof import('./src/components/tools/index.vue')['default']
    Workspace: typeof import('./src/components/workspace/index.vue')['default']
  }
}
